config/routes.rb
require 'sidekiq/web'

Tagsurf::Application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { 
                       registrations: 'registrations', 
                       sessions: 'sessions',  
                       passwords: 'passwords',
                       :omniauth_callbacks => "omniauth_callbacks"
                     }

  get 'users/sign_up', to: redirect('/sign-up')
 
  # Static Routes
  get 'feed'            => 'client#feed'
  get 'share/:tag'      => 'client#share'
  get 'share/:tag/:id'  => 'client#share'
  get 'history'         => 'client#history'
  get 'favorites'       => 'client#favorites'
  get 'submissions'     => 'client#submissions'
  get 'bumps'           => 'client#bumps'
  get 'tag'             => 'client#tag'
  get 'bump/:ref_id'    => 'client#bump'
  get 'contacts'        => 'client#contacts'

  #Enable Push
  get 'push-enable/:user_id'  => 'client#push_enable'
  get 'push'                  => 'client#push'

  # Beta access flow, ordered by good path
  get 'code'               => 'client#access_code'
  get 'disclaimer'         => 'client#disclaimer'
  get 'terms'              => 'client#terms'
  get 'sign-up'            => 'client#signup'
  get 'resend'             => 'client#resend_link'
  get 'welcome'            => 'client#welcome'
  get 'selectusername'     => 'client#username_select'
  get 'linkfb'             => 'client#linkfb'
  get 'name'               => 'client#enter_name'
  get 'phone'              => 'client#enter_phone'
  get 'confirm'            => 'client#confirm'
  get 'linkcontacts'       => 'client#link_contacts'
  get 'addresslink'        => 'client#addressbook'
    
  # Multi-step beta access flow
  post 'confirm-beta'              => 'client#confirm_beta_token'
  post 'confirm-disclaimer'        => 'client#disclaimer_agreement'
  post 'confirm-terms'             => 'client#terms_agreement'
  post 'sms'                       => 'sms#receive'

  # User routes
  put 'user'                        => 'users#update'
  post 'authentication/from-native' => 'users#from_native'
  post 'phone/verify/:user_id'      => 'confirmation_codes#verify_code'


  # JSON API
  namespace :api do
  
    get 'card/:id' => 'media#show'

    # Media API
    get  'media/:tag'                       => 'media#next'
    get  'share/:tag/:id/:limit/:offset'    => 'media#share_feed'
    post 'media/:media_id/tags/:name/'      => 'tags#create'
    post 'media/:media_id/report'           => 'media#report'
    get  'media/:media_id/unreport'         => 'media#remove_report'

    # Tags API
    get  'tags'                          => 'tags#tag_feed'
    get  'tags/search'                   => 'tags#search'
    get  'tags/:name'                    => 'tags#show'

    # Vote API
    get  'votes'                         => 'votes#show'
    post 'votes/:vote/:id/tag/:tag'      => 'media#create_vote'

    # Users API
    get  'users/:id/stats'               => 'votes#stats'
    get  'users'                         => 'users#stats'
    get  'users/list'                    => 'users#list'
    get  'users/buddies'                 => 'users#buddies'
    patch  'users/:id'                   => 'users#update'
    get 'users/unsubscribe/:id/:type'    => 'users#unsubscribe'
    get 'users/check-name/:username'     => 'users#check_username'

    # History API
    get  'history/paginated/:limit/:offset'  => 'users#paginated_history'
    get  'history/bracketed/:id'             => 'users#bracketed_history'
    get  'history/next/:id'                  => 'users#next_history'
    get  'history/previous/:id'              => 'users#previous_history'

    # Favorites API
    get  'favorites/paginated/:limit/:offset'      => 'favorites#paginated_history'
    get  'favorites/bracketed/:id'                 => 'favorites#bracketed_history'
    get  'favorites/next/:id'                      => 'favorites#next_history'
    get  'favorites/previous/:id'                  => 'favorites#previous_history'
    post 'favorites/:card_id'                      => 'favorites#create'
    delete 'favorites/:card_id'                    => 'favorites#delete'

    # Referrals API
    get  'referral/made/paginated/:limit/:offset'         => 'referrals#paginated_collection_made'
    get  'referral/received/paginated/:limit/:offset'     => 'referrals#paginated_collection_received'
    post 'referral/:card_id/:user_ids'                    => 'referrals#create'
    post 'referral/:card_id/:referral_id'                 => 'referrals#bump'
    get 'referral/seen/:referral_id'                      => 'referrals#seen'

    #Bumps API
    post 'bump/:media_id/:sharer_ids'       => 'bumps#create'
    get 'bump/seen/:bump_id'                => 'bumps#seen'

    # Friends API
    post 'friend/request/:user_id'          => 'friends#create'
    post 'friend/accept/:user_id'           => 'friends#accept'
    post 'friend/decline/:user_id'          => 'friends#decline'
    post 'friend/unfriend/:user_id'         => 'friends#destroy'

    post 'contacts'                         => 'friends#match_contacts'

  end

  get '/desktop' => 'client#desktop'

  root to: "client#index"

end

app/controllers/client_controller.rb
class ClientController < ApplicationController

  before_action :authenticate_user!, except: [
    :index, 
    :access_code,
    :confirm_beta_token, 
    :disclaimer,
    :terms,
    :share,
    :signup,
    :disclaimer_agreement,
    :terms_agreement,
    :password_submission,
    :authentication
  ]

  before_action :confirm_surfable, only: [
    :feed, 
    :favorites, 
    :trending, 
    :history, 
    :submissions, 
    :tag
  ] 

  layout 'client'

  def index
    # Decide how to direct the user base on state
    usr = current_user
    unless !usr 
      # if !usr.welcomed?
      #   redirect_to welcome_path
      if !usr.username
        redirect_to selectusername_path
      # elsif !usr.fb_link_requested && !usr.profile_pic_link
      #   redirect_to linkfb_path
      # elsif !usr.first_name
      #   redirect_to name_path
      # elsif !usr.phone
      #   redirect_to phone_path
      # elsif !usr.phone_confirmed
      #   redirect_to confirm_path
      elsif !usr.push_requested && params[:id].to_i == 0
        redirect_to "/push##{current_user.id}"
      # elsif !usr.contacts_link_requested
      #   redirect_to linkcontacts_path
      else
        redirect_to feed_path
      end
      return
    end
    redirect_to user_session_path
  end

  # !!! Deprecated !!!
  # Beta access post requests
  # Multi-setp form throug POST requests

  # Step one
  def confirm_beta_token
    code = AccessCode.where(code: beta_code_params[:access_code]).first
    if code && code.valid_code?
      redirect_to "/terms?code=#{code.code}&d_accept=true"
    else
      flash[:error] = ["Invalid beta code."]
      redirect_to :root
    end
  end

  # Step two
  def terms_agreement
    code = AccessCode.where(code: beta_code_params[:access_code]).first.code
    terms = beta_code_params[:t_accept] 
    email = beta_code_params[:email]

    unless email.present?
      flash[:error] = ["Enter an email to continue."] 
      redirect_to "/terms?code=#{code}&d_accept=true"
      return
    end

    if User.where(email: email).exists?
      flash[:error] = ["Email address already registered."]
      redirect_to "/terms?code=#{code}&d_accept=true"
      return
    end
    
    if terms == 'true' and code.present? and email.present?
      redirect_to "/sign-up?code=#{code}&d_accept=true&t_accept=true&email=#{email}"
    else
      redirect_to "/terms?code=#{code}&d_accept=true", error: 'Please enter your email.'
    end
  end

  ### End beta access 

  # Static application
  def trending; end
  def feed;
    flash.discard(:notice)
    expires_in 30.days, public: true;
  end
  def favorites;
    expires_in 30.days, public: true;
  end
  def history; 
    expires_in 30.days, public: true;
  end
  def submissions; end
  def bumps;
    expires_in 30.days, public: true;
  end
  def tag; end
  def device; end

  # Beta access flow
  def access_code; end
  def disclaimer; end
  def terms; end
  def signup; end
  def authentication; end

  def share
    usr = current_user

    case params["id"].to_i
    when 0
      if usr 
        if !usr.username
          redirect_to selectusername_path
        elsif !usr.phone
          redirect_to phone_path
        elsif !usr.phone_confirmed
          redirect_to confirm_path
        elsif !usr.push_requested and params[:id].to_i == 0
          redirect_to "/push##{usr.id}"
        elsif !usr.fb_link_requested and !usr.profile_pic_link
          redirect_to linkfb_path
        elsif !usr.first_name
          redirect_to name_path
        elsif !usr.contacts_link_requested
          redirect_to linkcontacts_path
        elsif params[:tag] == "trending" 
          redirect_to "/feed#funny~#{params["id"]}"
        else
          redirect_to "/feed##{params["tag"]}~#{params["id"]}"         
        end
      else
        confirm_surfable
      end
    else
      if usr 
        redirect_to "/feed##{params["tag"]}~#{params["id"]}"
      end
    end
    
    @media = Media.where(id: params[:id]).try(:first)
  end

  def push_enable
    user = User.find(current_user.id)
    user.update_column :push_requested, true
    redirect_to root_path   
  end

  def push
  end

  def bump
    unless !current_user || current_user.id != Referral.unscoped.find(params[:ref_id]).user_id
      Bump.bump_referral(params[:ref_id])
    end 
    media_id = Referral.unscoped.find(params[:ref_id]).media_id
    redirect_to "/feed#funny~#{media_id}"
  end
  
  def resend_link 
    if current_user and current_user.confirmed? 
      redirect_to root_path
    end
  end

  def welcome
    if current_user.welcomed?
      redirect_to root_path
    end
  end

  def username_select 
    @user = current_user
  end 

  def linkfb
    user = User.find(current_user.id)
    user.update_column :fb_link_requested, true
  end

  def enter_name
    @user = current_user
  end

  def enter_phone
    @user = current_user
    unless @user.confirmation_code
      ConfirmationCode.create(:user_id => @user.id).save
    end
  end

  def confirm
    @user = current_user
    @code
  end

  def link_contacts
  end

  def addressbook
    user = User.find(current_user.id)
    user.update_column :contacts_link_requested, true
  end

  private

    def beta_code_params
      params.require(:access_code).permit(
        :access_code, 
        :d_accept, 
        :t_accept, 
        :email, 
        :password, 
        :password_confirmation
      )
    end

    def confirm_surfable
      unless current_user
        redirect_to root_path
      end
    end

end

app/views/client/addressbook.html.erb
<%= stylesheet_link_tag "sessions", :media => "all" %>

<center>
	<div id='container'>
  	<div class="tslogo"></div>
  	<div class="ac-text-container">	
  		<p>Find friends from<br/>your contacts list!</p>
  	</div>
		<a id='btn-lnk' href = 'addressbook://'><div id='btn' class="button" style="max-width: 40%; margin-top: 20px; font-size: 120%; font-weight: 300;", onclick="connect();">Ok</div></a>
		<a id='btn-lnk' href = '/'><div id='btn' class="button" style="max-width: 40%; margin-top: 20px; font-size: 120%; font-weight: 300;", onclick="throbber.on();">Not Now</div></a>
	</div>
</center>

<%= javascript_include_tag "push" %>

<script type="text/javascript">
	var connect = function () {
		throbber.on();
		var link = document.getElementById('btn-lnk'),
				dispatch = document.createEvent("HTMLEvents");

		dispatch.initEvent("click", true, true);
		link.dispatchEvent(dispatch);
	}
</script>

app/views/client/bumps.html.erb
<% content_for :title do %>
  <title>tagSurf - Shares</title>
<% end %>

<!-- Place body html below -->
<div id="nav"></div>

<%= javascript_include_tag "gallery_page" %>
<% content_for :javascripts do %>
  <script>
    populateNavbar();
    gallerize("bumps");
  </script>
<% end %>

app/views/client/enter_name.html.erb
<%= stylesheet_link_tag "sessions", :media => "all" %>

<%= form_for(@user, :url => user_path(@user), :remote => false, :html => {:method => 'put', :role => 'form', :id => 'name_form'}) do |f| %>
  <center>
   <div class="tslogo"></div>
   <div class="ac-text-container">
    <p>Help your friends find you! <br/>Tell us your name.</p>
   </div>
  <div>
    <div class="input-border-container" style="margin-bottom:10px;"><%= f.text_field :first_name, placeholder: "first name", autocomplete: "off", spellcheck: "false", autocapitalize: "on", autocorrect: "off", class: 'ts-input' %></div>
    <div class="input-border-container" style="margin-bottom:10px;"><%= f.text_field :last_name, placeholder: "last name", autocomplete: "off", spellcheck: "false", autocapitalize: "on", autocorrect: "off", class: 'ts-input' %></div> 
  </div>

  <%= f.submit "Submit", id: "submit-btn", class: "button input-width", style: "margin-top:5px; font-size: 120%; font-weight: 300;" %>

  </center>
<% end %>

<%= javascript_include_tag "sessions" %>
<script type="text/javascript">
  var inputs = document.getElementsByClassName("ts-input");
  stroke.listen("up", "13", function() {
    f.submit();
  });
  fadeInBody();
  inputs[0].onfocus = function () { toggleClass.apply(inputs[0].parentNode, ["focused"]); };
  inputs[0].onblur = function () { toggleClass.apply(inputs[0].parentNode, ["focused"]); };
  inputs[1].onfocus = function () { toggleClass.apply(inputs[1].parentNode, ["focused"]); };
  inputs[1].onblur = function () { toggleClass.apply(inputs[1].parentNode, ["focused"]); };
</script>

app/views/client/index.html.erb
<center>
 <img id="tslogo" src="http://assets.tagsurf.co/img/ts_logo_stacked_gray.png"></img>
 <input id="email" class="ts-input" placeholder="email">
 <input id="password" class="ts-input" placeholder="password" type="password">
</center>
<div class="ts-submit-bar">
 <div class="ts-submit-btn">
  <div class="border-trim">
   <input id="ts-login-btn" type="submit" value="log in">
  </div>
 </div>
 <div class="ts-submit-btn">
  <a class="ts-signup-btn">sign up</a>
 </div>
</div>

app/views/client/link_contacts.html.erb
<%= javascript_include_tag "push" %>

<script type="text/javascript">
	if (isUIWebView() && !isAndroid())
		document.location = '/addresslink';
	else
		document.location = '/feed#funny';
</script>

app/views/client/linkfb.html.erb
<%= stylesheet_link_tag "sessions", :media => "all" %>

<center>
	<div id='container'>
   <div class="tslogo"></div>
   <div class="ac-text-container">
		<p>Link or refresh your facebook account to load your profile pic</p>
   </div>
	 <a id='btn-lnk' href = '/users/auth/facebook'><div id='btn' class="button" style="max-width: 40%; margin-top: 20px; font-size: 120%; font-weight: 300;">Ok</div></a>
	 <a id='btn-lnk' href = '/'><div id='btn' class="button" style="max-width: 40%; margin-top: 20px; font-size: 120%; font-weight: 300;">Not Now</div></a>
	</div>
</center>

app/views/client/push.html.erb
<%= stylesheet_link_tag "sessions", :media => "all" %>

<center>
	<div id='container' class='hidden'>
   <div class="tslogo"></div>
   <div class="ac-text-container">
		<p>Please enable push notificaitons to see when your friends share with you</p>
   </div>
	 <a id='btn-lnk'><div id='btn' class="button" style="max-width: 30%;">Ok</div></a>
	</div>
</center>

<%= javascript_include_tag "push" %>

<script type="text/javascript">
	if (isUIWebView() && !isAndroid()) { //&& document.location.hash.split('~')[1]) {
		var container = document.getElementById('container'),
			button = document.getElementById('btn-lnk'),
			user_id = document.location.hash.split('#')[1].split('~')[0];
			// model = document.location.hash.split('~')[1];
		container.classList.remove('hidden');
		button.setAttribute('href', "/push-enable/" + user_id);
		// if (model && model.indexOf('iPhone7') == -1) {
		// 	button.setAttribute('target', '_blank');
		// }
	}
	else
		document.location = '/feed#funny';
</script>

app/views/client/recommendations.html.erb
<% content_for :title do %>
  <title>tagSurf - Recommendations</title>
<% end %>

<!-- Place body html below -->
<div id="nav"></div>

<%= javascript_include_tag "gallery_page" %>
<% content_for :javascripts do %>
  <script>
    populateNavbar();
    gallerize("recommendations");
  </script>
<% end %>

app/views/client/resend_link.html.erb
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/beta.css">
<div class="centered">
 <img class="toplogo" src="http://assets.tagsurf.co/img/ts_logo_horiz_gray.png">
 <div class="bigger">
  <div class="midpad">
   Please verify your email account to complete your beta registration.
  </div>
  <div class="midpad">
   A verification link has been sent to:
  </div>
  <div class="midpad">
   <%= current_user.email %>
  </div>
 </div>
 <div class="biggest bottom">

  <%= form_for(User.new, :as => :user, :url => confirmation_path(:user), :html => { :method => :post }) do |f| %>
    <%= f.hidden_field :email, value: current_user.email %>
    <%= f.submit "Resend link", class: 'button' %>
  <% end %>

 </div>
</div>

app/views/client/share.html.erb
<% content_for :title do %>
  <title>tagSurf - Share</title>
<% end %>

<!-- Place body html below -->
<div id="nav" ontouchmove="return false;"></div>
<div id="formatter" class="hider"></div>
<div id="scroll-container-container">
	<div id="scroll-container">
	  <div id="input-container">
	    <div id="static-icon">
	      <span id="static-hash" class="bold">#</span>
	    </div>
	    <input id="tag-input" type="text" spellcheck="false" autocomplete="off" autocapitalize="off" autocorrect="off">
	    <div id="search-input"><img src="http://assets.tagsurf.co/img/search_white.png"></div>
	  </div>
	  <div id="slider"></div>
	</div>
</div>
<div id="autocomplete" class="autocomplete hider"></div>

<%= javascript_include_tag "application" %>

app/views/client/shares.html.erb
<% content_for :title do %>
  <title>tagSurf - Shares</title>
<% end %>

<!-- Place body html below -->
<div id="nav"></div>

<%= javascript_include_tag "gallery_page" %>
<% content_for :javascripts do %>
  <script>
    populateNavbar();
    gallerize("shares");
  </script>
<% end %>

app/views/client/signup.html.erb
<%= stylesheet_link_tag "sessions", :media => "all" %>

<div class="scroller">

<%= form_for(User.new, :as => :user, :url => registration_path(:user) ) do |f| %>
  <center>
    <img class="tslogo" src="http://assets.tagsurf.co/img/ts_logo_stacked_gray.png"></img>
    <div class="su-container">

      <div class="su-input-container light-bottom-margin">
        <%= f.email_field :email, :placeholder => 'email', :class => 'su-input bigplace', id: 'email', autocomplete: "off", spellcheck: "false", autocapitalize: "off", autocorrect: "off" %>
      </div>

      <small class="su-helper-txt">Password must be at least 8 characters</small>

      <div class="su-input-container">
        <%= f.password_field :password, :placeholder => 'password', :class => 'su-input bigplace', id: 'password', autocomplete: "off", spellcheck: "false", autocapitalize: "off", autocorrect: "off" %>
      </div>

      <div class="su-input-container">
        <%= f.password_field :password_confirmation, :placeholder => 're-enter password', :class => 'su-input bigplace', id: 'repassword', autocomplete: "off", spellcheck: "false", autocapitalize: "off", autocorrect: "off" %>
      </div>

      <%= f.submit 'Submit', id: 'su-submit-btn' %>
      
    </div>
  </center>
<% end %>

<%= link_to "<span class='ts-blue'>Already have an account?</span> Login here.".html_safe, '/users/sign_in', class: 'link-to-login twelve light-gray' %>

<small class="su-helper-txt disclaimer">By registering with tagSurf you agree to our <div class="disclaimer-link inline bold" id="terms-lnk">Terms of Use</div> and <div class="disclaimer-link inline bold" id="privacy-lnk">Privacy Policy</div>.</small>

</div>

<%= javascript_include_tag "signup" %>

<script>
document.body.style.width = "100%";
var inputs = document.getElementsByClassName("su-input");
inputs[0].onfocus = function () { toggleClass.apply(inputs[0].parentNode, ["focused"]); };
inputs[0].onblur = function () { toggleClass.apply(inputs[0].parentNode, ["focused"]); };
inputs[1].onfocus = function () { toggleClass.apply(inputs[1].parentNode, ["focused"]); };
inputs[1].onblur = function () { toggleClass.apply(inputs[1].parentNode, ["focused"]); };
inputs[2].onfocus = function () { toggleClass.apply(inputs[2].parentNode, ["focused"]); };
inputs[2].onblur = function () { toggleClass.apply(inputs[2].parentNode, ["focused"]); };
addCss({
  ".scroller": function() {
    return "height: " + window.innerHeight + "px;";
  }
});
initDocLinks();
</script>

app/views/client/tag.html.erb
<% content_for :title do %>
  <title>tagSurf - Tag</title>
<% end %>

<!-- Place body html below -->
<div id="nav"></div>

<%= javascript_include_tag "gallery_page" %>

<% content_for :javascripts do %>
  <script>
    populateNavbar();
    gallerize("tag");
  </script>
<% end %>

app/views/client/username_select.html.erb
<%= stylesheet_link_tag "sessions", :media => "all" %>

<%= form_for(@user, :url => user_path(@user), :remote => false, :html => {:method => 'put', :role => 'form', :id => 'username_form'}) do |f| %>
  <center>
   <div class="tslogo"></div>
   <div class="ac-text-container">
    <p>Pick your surfer name!</p>
   </div>
  <div class="input-border-container" style="margin-bottom:10px;">
    <%= f.text_field :username, placeholder: "username", autocomplete: "off", spellcheck: "false", autocapitalize: "off", autocorrect: "off", class: 'ts-input' %>
    <div id="check-indicator" class="available hidden">&#10003</div>  
  </div>

  <div id='submit-btn' class="button input-width disabled-button", onclick="form_submit();">Submit</div>

  </center>
<% end %>

<%= javascript_include_tag "sessions" %>

<script type="text/javascript">
  var inputs = document.getElementsByClassName('ts-input');

  var check_availability = function() {
    var username = document.getElementById('user_username').value.trim();

    xhr('/api/users/check-name/' + username, 'Get', function(response) {
    }, null);
    console.log(available);
  };

  var form_submit = function() {
    var username = document.getElementById('user_username').value.trim(),
    f = document.getElementById('username_form');
    if(username == "")
      alert('Please pick a surfer name');
    xhr('/api/users/check-name/' + username, 'Get', function(response) {
      if (response.users[0].available)
        f.submit()
      else
        alert('That surfer name is already taken :(');
    }, null);
  }

  stroke.listen("up", "13", function() {
    form_submit();
  });

  stroke.listen("up", null, function() {
    var username = document.getElementById('user_username').value,
        indicator = document.getElementById('check-indicator'),
        button = document.getElementById('submit-btn');

    if (username == "") {
      if (!indicator.classList.contains('hidden'))
        indicator.classList.add('hidden');
      if (!button.classList.contains('disabled-button'))
        button.classList.add('disabled-button');
    } 
    else {
      xhr('/api/users/check-name/' + username, 'Get', function(response) {
        if (response.users[0].available) {
          if (indicator.classList.contains('hidden'))
            indicator.classList.remove('hidden');
          if (button.classList.contains('disabled-button'))
            button.classList.remove('disabled-button');
          if (indicator.classList.contains('unavailable')){
            indicator.classList.remove('unavailable');
            indicator.classList.add('available');
          }
          indicator.innerHTML = "&#10003";
        }
        else {
          if (indicator.classList.contains('hidden'))
            indicator.classList.remove('hidden');
          if (!button.classList.contains('disabled-button'))
            button.classList.add('disabled-button');
          if (indicator.classList.contains('available')){
            indicator.classList.remove('available');
            indicator.classList.add('unavailable');
          }
          indicator.innerHTML = "X";
        }
      }, null);
    }
  });

  inputs[0].onfocus = function () { toggleClass.apply(inputs[0].parentNode, ["focused"]); };
  inputs[0].onblur = function () { toggleClass.apply(inputs[0].parentNode, ["focused"]); };

</script>